server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
                
eureka:
  instance:
    non-secure-port: 0

spring:
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config/{application}/{profile}
          add-label-locations: false