server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/api/'+serviceId.toLowerCase()+'/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'/api/' + serviceId.toLowerCase() + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
      routes:
      - id: admin-ui
        uri: lb://admin-ui
        predicates:
        - Path=/admin/**
        filters:
        - StripPrefix=1
    loadbalancer:
      cache:
        enabled: false